### ISSUE TITLE
Cannot load plpgsql when creating opm_core extension on 11 devel

### ISSUE THREAD

**Issue by PauloLaScience** [OPMDG/opm-core#53]
Hi,
I'm trying to install opm on PostgreSQL version 11 Devel and I get an error when I'm trying to 
`CREATE EXTENSION opm-core;`

```
postgres@debpg11:~$ psql
psql (11devel (Debian 11~~devel~20180418.2231-1~573.git5372c2c.pgdg90+1))
Type "help" for help.

postgres=# CREATE DATABASE opm;
CREATE DATABASE
postgres=# \c opm
You are now connected to database "opm" as user "postgres".
opm=# CREATE EXTENSION opm_core;
ERROR:  could not load library "/usr/lib/postgresql/11/lib/plpgsql.so": /usr/lib/postgresql/11/lib/plpgsql.so: undefined symbol: MemoryContextSetIdentifier
```

Regards,
Paul-Emmanuel Devadder
[@PaulemDevadder](https://twitter.com/PaulemDevadder)

**Comment by rjuju** [comment]
Hi,

It doesn't really looks related to opm-core, especially since the extension is only written in plpgsql.  I also can't reproduce it on a local pg11 server.

MemoryContextSetIdentifier was added in pg11 on 2018-03-27, and your Debian snapshot looks more recent, at least for the client binaries.

Are you connecting to a freshly compiled server, or is it also debian packaged?  Can you check if you can actually declare and execute plpgsql functions on this server?

**Comment by PauloLaScience** [comment]
Hi,
It's a Debian packaged on apt.postgresql.org stretch-pgdg-testing. I will try again with the latest build. I was not able to reproduce on pg 10.3

Regards,
[@PaulemDevadder](https://twitter.com/PaulemDevadder)

**Comment by PauloLaScience** [comment]
Hi, I try this simple function and I get the same error.
I will return this issue to Postgres testing
```
postgres=# CREATE FUNCTION sum_of_two_numbers(m integer, n integer)
postgres-# RETURNS integer AS $$
postgres$#         BEGIN
postgres$#                 RETURN m + n;
postgres$#         END;
postgres$# $$ LANGUAGE plpgsql;
ERROR:  could not load library "/usr/lib/postgresql/11/lib/plpgsql.so": /usr/lib/postgresql/11/lib/plpgsql.so: undefined symbol: MemoryContextSetIdentifier
postgres=#
```

**Comment by rjuju** [comment]
Hi,

Thanks for the confirmation!
